### ISSUE TITLE
CocoaPods version is still 1.3

### ISSUE THREAD

**Issue by Kaspik** [VivienCormier/UIImageViewModeScaleAspect#9]
Hello, could you please update CocoaPods version to 1.4 also? Thanks! :)

**Comment by VivienCormier** [comment]
Hey,

I pushed the last version (1.4) to cocoapods!

**Comment by Kaspik** [comment]
Okay, thanks! But for me it still doesn't work... I'll try to investigate more, but I didn't change anything. 😕

**Comment by VivienCormier** [comment]
What doesn't work for you?

You can't get the new version 1.4 from Cocoapod or the plugin 'UIImageViewModeScaleAspect' doesn't work for you?

**Comment by Kaspik** [comment]
Well, the library.

Here is some code:
```
UIImageViewModeScaleAspect *imageView = [[UIImageViewModeScaleAspect alloc] initWithFrame:self.fromFrame];
        imageView.image = self.imageToAnimate;
        
        if (self.fromView.contentMode == UIViewContentModeScaleAspectFit) {
            [imageView initToScaleAspectFitToFrame:self.toFrame];
            [imageView setFrame:self.fromFrame];
        } else {
            [imageView initToScaleAspectFitToFrame:self.toFrame];
        }

        [self.containerView addSubview:imageView];
        [UIView animateWithDuration:self.animationDuration animations:^{
            [imageView animaticToScaleAspectFit];
            self.containerView.backgroundColor = [UIColor blackColor];
            self.backgroundView.alpha = 1.f;
		} completion:^(BOOL finished) {
            CGRect rect = CGRectMake(0.0f, 0.0f, [UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height);
            toViewController.view.frame = rect;
            [self.containerView addSubview:toViewController.view];
            self.cellImageView.image = nil;
            
            [self.backgroundView removeFromSuperview];
            [imageView removeFromSuperview];
            
            [transitionContext completeTransition:YES];
		}];
```

And here is the video. (frames are correct - middle of the "photo preview").
[aspectmode.zip](https://github.com/VivienCormier/UIImageViewModeScaleAspect/files/350833/aspectmode.zip)

**Comment by VivienCormier** [comment]
Can you try with this code? it contains a lot of duplicate code, but it can work better.

`UIImageViewModeScaleAspect *imageView = [[UIImageViewModeScaleAspect alloc] initWithFrame:self.fromFrame];
    imageView.image = self.imageToAnimate;
    
    if (self.fromView.contentMode == UIViewContentModeScaleAspectFit) {
        [imageView initToScaleAspectFillToFrame:self.toFrame];
        
        [self.containerView addSubview:imageView];
        
        [UIView animateWithDuration:self.animationDuration animations:^{
            [imageView animaticToScaleAspectFill];
            self.containerView.backgroundColor = [UIColor blackColor];
            self.backgroundView.alpha = 1.f;
        } completion:^(BOOL finished) {
            CGRect rect = CGRectMake(0.0f, 0.0f, [UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height);
            toViewController.view.frame = rect;
            [self.containerView addSubview:toViewController.view];
            self.cellImageView.image = nil;
            [self.backgroundView removeFromSuperview];
            [imageView removeFromSuperview];
            [transitionContext completeTransition:YES];
        }];
        
    } else {
        
        [imageView initToScaleAspectFitToFrame:self.toFrame];
        
        [self.containerView addSubview:imageView];
        
        [UIView animateWithDuration:self.animationDuration animations:^{
            [imageView animaticToScaleAspectFit];
            self.containerView.backgroundColor = [UIColor blackColor];
            self.backgroundView.alpha = 1.f;
        } completion:^(BOOL finished) {
            CGRect rect = CGRectMake(0.0f, 0.0f, [UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height);
            toViewController.view.frame = rect;
            [self.containerView addSubview:toViewController.view];
            self.cellImageView.image = nil;
            [self.backgroundView removeFromSuperview];
            [imageView removeFromSuperview];
            
            [transitionContext completeTransition:YES];
        }];
        
    }`

**Comment by Kaspik** [comment]
Well, as I see - there is no change from your side for the first part. It was only small part for presenting - this is for presenting and dismissing. I think you didn't change anything. 😄 

```
if (!self.isPresenting) {
		self.containerView.backgroundColor = [UIColor clearColor];
		self.presenting = YES;
        
        self.backgroundView.backgroundColor = self.toViewControllerBackgroundColor;
        self.backgroundView.alpha = 0.f;
        [self.containerView addSubview:self.backgroundView];
        [self.containerView removeConstraints:self.containerView.constraints];

        NSDictionary *view = @{@"backgroundView" : self.backgroundView};
        [self.containerView addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|[backgroundView]|" options:NSLayoutFormatDirectionLeftToRight metrics:nil views:view]];
        [self.containerView addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|[backgroundView]|" options:NSLayoutFormatDirectionLeftToRight metrics:nil views:view]];
        
        UIImageViewModeScaleAspect *imageView = [[UIImageViewModeScaleAspect alloc] initWithFrame:self.fromFrame];
        imageView.image = self.imageToAnimate;
        
        if (self.fromView.contentMode == UIViewContentModeScaleAspectFit) {
            [imageView initToScaleAspectFitToFrame:self.toFrame];
            [imageView setFrame:self.fromFrame];
        } else {
            [imageView initToScaleAspectFitToFrame:self.toFrame];
        }

        [self.containerView addSubview:imageView];
        [UIView animateWithDuration:self.animationDuration animations:^{
            [imageView animaticToScaleAspectFit];
            self.containerView.backgroundColor = [UIColor blackColor];
            self.backgroundView.alpha = 1.f;
		} completion:^(BOOL finished) {
            CGRect rect = CGRectMake(0.0f, 0.0f, [UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height);
            toViewController.view.frame = rect;
            [self.containerView addSubview:toViewController.view];
            self.cellImageView.image = nil;
            
            [self.backgroundView removeFromSuperview];
            [imageView removeFromSuperview];
            
            [transitionContext completeTransition:YES];
		}];
	} else {
		[self updateAnimationFrames];

		self.presenting = NO;
        
		self.backgroundView.backgroundColor = [UIColor clearColor];
		
		[self.containerView addSubview:self.backgroundView];
        [self.containerView removeConstraints:self.containerView.constraints];
        
        NSDictionary *view = @{@"backgroundView" : self.backgroundView};
        [self.containerView addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|[backgroundView]|" options:NSLayoutFormatDirectionLeftToRight metrics:nil views:view]];
        [self.containerView addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|[backgroundView]|" options:NSLayoutFormatDirectionLeftToRight metrics:nil views:view]];
        
        
		UIImageViewModeScaleAspect *imageView = [[UIImageViewModeScaleAspect alloc] initWithFrame:self.imgFrame];
		imageView.image = self.imageToAnimate;
        imageView.contentMode = UIViewContentModeScaleAspectFit;
        
        [imageView initToScaleAspectFillToFrame:self.fromFrame];
        
		[self.containerView addSubview:imageView];
        
        [fromViewController.view removeFromSuperview];
        
        [UIView animateWithDuration:self.animationDuration animations:^{
            [imageView animaticToScaleAspectFill];
            if (IS_OS_8_OR_LATER) {
                self.containerView.backgroundColor = [[UIColor clearColor] colorWithAlphaComponent:0.0f];
            }
            //imageView.frame = self.fromFrame;
            
        } completion:^(BOOL finished) {
            self.cellImageView.image = self.imageToAnimate;
            for (UIView *view in  transitionContext.containerView.subviews) {
                [view removeFromSuperview];
            }
            [transitionContext completeTransition:YES];
            [fromViewController viewDidDisappear:TRUE];
        }];
	}
```

**Comment by VivienCormier** [comment]
Ok I see. If you can reproduce the bug inside a sample app, I'll be happy to help you to fix this bug.

**Comment by Kaspik** [comment]
I will try that tomorrow, thanks!

**Comment by Kaspik** [comment]
@VivienCormier Okay, created new issue here: https://github.com/VivienCormier/UIImageViewModeScaleAspect/issues/10

I'll clean the code here.
